config/routes.rb
Rails.application.routes.draw do
  resources :klines do
    collection do
      post 'process_and_save'
    end
  end
  # Custom
  get 'crypto', to: 'crypto#index'
  get 'analyze', to: 'crypto#analyze'
  

  # Base
  resources :people
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'test', to: 'clients#test'

  devise_for :users
  # Allows us to use link_to for session destroy
  devise_scope :user do
    get "/users/sign_out", as: "sign_out", to: "devise/sessions#destroy"
  end

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/person.rb
class Person < ApplicationRecord
  enum document_type: { ci: 'CI', ruc: 'RUC', foreigner: 'EXTRANJERO' }, _prefix: true
  def document_type_t
    return 'CI' if document_type_ci?
    return 'RUC' if document_type_ruc?
    'Extranjero' if document_type_foreigner?
  end

  enum person_type: { natural: 'FISICA', legal: 'JURIDICA' }, _prefix: true
  def person_type_t
    return 'Física' if person_type_natural?
    'Jurídica' if person_type_legal?
  end

  def full_document
    "#{document_type_t} - #{document_number + (verifying_digit || '')}"
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[ show edit update destroy ]

  # GET /people or /people.json
  def index
    @people = Person.all
  end

  # GET /people/1 or /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to person_url(@person), notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to person_url(@person), notice: "Person was successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url, notice: "Person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:person_type, :name, :document_number, :verifying_digit, :document_type)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_with(model: person) do |form| %>
  <% if person.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :person_type, style: "display: block" %>
    <%= form.text_field :person_type %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :document_number, style: "display: block" %>
    <%= form.text_field :document_number %>
  </div>

  <div>
    <%= form.label :verifying_digit, style: "display: block" %>
    <%= form.text_field :verifying_digit %>
  </div>

  <div>
    <%= form.label :document_type, style: "display: block" %>
    <%= form.text_field :document_type %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/people/_person.html.erb
<tr>
  <td><%= person.name %></td>
  <td><%= person.person_type_t %></td>
  <td><%= person.document_type_t %></td>
  <td><%= person.full_document %></td>
  <td>
    <div class="table-actions d-flex align-items-center gap-3 fs-6">
      <%= render(GridActionViewComponent.new(url: person_path(person))) %>
      <%= render(GridActionEditComponent.new(url: edit_person_path(person))) %>
      <%= render(GridActionDeleteComponent.new(url: person_path(person))) %>
    </div>
  </td>
</tr>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Show this person", @person %> |
  <%= link_to "Back to people", people_path %>
</div>

app/views/people/index.html.erb
<h1>Peronas</h1>

<%= link_to "Nueva Persona", new_person_path, class: "btn btn-primary px-5" %>

<div class="table-responsive mt-3">
  <table class="table align-middle">
    <thead class="table-secondary">
      <tr>
      <th>Nombre</th>
      <th>Tipo Persona</th>
      <th>Tipo Documento</th>
      <th>Documento</th>
      <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      <% @people.each do |person| %>
        <%= render person %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Back to people", people_path %>
</div>

app/views/people/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @person %>

<div>
  <%= link_to "Edit this person", edit_person_path(@person) %> |
  <%= link_to "Back to people", people_path %>

  <%= button_to "Destroy this person", @person, method: :delete %>
</div>