config/routes.rb
Rails.application.routes.draw do
  resources :klines do
    collection do
      post 'process_and_save'
    end
  end
  # Custom
  get 'crypto', to: 'crypto#index'
  get 'analyze', to: 'crypto#analyze'
  

  # Base
  resources :people
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'test', to: 'clients#test'

  devise_for :users
  # Allows us to use link_to for session destroy
  devise_scope :user do
    get "/users/sign_out", as: "sign_out", to: "devise/sessions#destroy"
  end

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/kline.rb
class Kline < ApplicationRecord
end

app/controllers/klines_controller.rb
class KlinesController < ApplicationController
  before_action :set_kline, only: %i[ show edit update destroy ]

  # GET /klines or /klines.json
  def index
    @klines = Kline.all
  end

  # GET /klines/1 or /klines/1.json
  def show
  end

  # GET /klines/new
  def new
    @kline = Kline.new
  end

  # GET /klines/1/edit
  def edit
  end

  # POST /klines or /klines.json
  def create
    @kline = Kline.new(kline_params)

    respond_to do |format|
      if @kline.save
        format.html { redirect_to kline_url(@kline), notice: "Kline was successfully created." }
        format.json { render :show, status: :created, location: @kline }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @kline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /klines/1 or /klines/1.json
  def update
    respond_to do |format|
      if @kline.update(kline_params)
        format.html { redirect_to kline_url(@kline), notice: "Kline was successfully updated." }
        format.json { render :show, status: :ok, location: @kline }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @kline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /klines/1 or /klines/1.json
  def destroy
    @kline.destroy!

    respond_to do |format|
      format.html { redirect_to klines_url, notice: "Kline was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # Custom method to process and save Kline data
  def process_and_save
    symbol = params[:symbol]
    kline_data = crypto_service.get_history(symbol)

    kline_data.each do |data|
      timestamp_s = data[0] / 1000.0
      open_time  = Time.at(timestamp_s)

      timestamp_s = data[6] / 1000.0
      close_time  = Time.at(timestamp_s)

      kline = Kline.find_by(symbol: symbol, open_time: open_time, close_time: close_time)
      data_params = {
        symbol: symbol,
        open_time: open_time,
        close_time: close_time,
        open: data[1].to_d,
        high: data[2].to_d,
        low: data[3].to_d,
        close: data[4].to_d,
        volume: data[5].to_d,
        quote_asset_volume: data[7].to_d,
        number_of_trades: data[8],
        taker_buy_base_asset_volume: data[9].to_d,
        taker_buy_quote_asset_volume: data[10].to_d
      }
      if kline
        puts "Ya existe kline: #{kline}"
        kline.update(data_params)
      else
        kline = Kline.create(data_params)
        
        puts "Nuevo kline creado: #{kline}"
      end
    end
    
    respond_to do |format|
      format.html { redirect_to crypto_path, notiche: 'Actuaizado' }
      format.json { render :index, status: :created }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kline
      @kline = Kline.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def kline_params
      params.require(:kline).permit(:symbol, :open_time, :open, :high, :low, :close, :volume, :close_time, :quote_asset_volume, :number_of_trades, :taker_buy_base_asset_volume, :taker_buy_quote_asset_volume)
    end

    def crypto_service
      @crypto_service ||= CryptoService.new
    end
end

app/helpers/klines_helper.rb
module KlinesHelper
end

app/views/klines/_form.html.erb
<%= form_with(model: kline) do |form| %>
  <% if kline.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(kline.errors.count, "error") %> prohibited this kline from being saved:</h2>

      <ul>
        <% kline.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :open_time, style: "display: block" %>
    <%= form.datetime_field :open_time %>
  </div>

  <div>
    <%= form.label :open, style: "display: block" %>
    <%= form.text_field :open %>
  </div>

  <div>
    <%= form.label :high, style: "display: block" %>
    <%= form.text_field :high %>
  </div>

  <div>
    <%= form.label :low, style: "display: block" %>
    <%= form.text_field :low %>
  </div>

  <div>
    <%= form.label :close, style: "display: block" %>
    <%= form.text_field :close %>
  </div>

  <div>
    <%= form.label :volume, style: "display: block" %>
    <%= form.text_field :volume %>
  </div>

  <div>
    <%= form.label :close_time, style: "display: block" %>
    <%= form.datetime_field :close_time %>
  </div>

  <div>
    <%= form.label :quote_asset_volume, style: "display: block" %>
    <%= form.text_field :quote_asset_volume %>
  </div>

  <div>
    <%= form.label :number_of_trades, style: "display: block" %>
    <%= form.number_field :number_of_trades %>
  </div>

  <div>
    <%= form.label :taker_buy_base_asset_volume, style: "display: block" %>
    <%= form.text_field :taker_buy_base_asset_volume %>
  </div>

  <div>
    <%= form.label :taker_buy_quote_asset_volume, style: "display: block" %>
    <%= form.text_field :taker_buy_quote_asset_volume %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/klines/_kline.html.erb
<div id="<%= dom_id kline %>">
  <p>
    <strong>Open time:</strong>
    <%= kline.open_time %>
  </p>

  <p>
    <strong>Open:</strong>
    <%= kline.open %>
  </p>

  <p>
    <strong>High:</strong>
    <%= kline.high %>
  </p>

  <p>
    <strong>Low:</strong>
    <%= kline.low %>
  </p>

  <p>
    <strong>Close:</strong>
    <%= kline.close %>
  </p>

  <p>
    <strong>Volume:</strong>
    <%= kline.volume %>
  </p>

  <p>
    <strong>Close time:</strong>
    <%= kline.close_time %>
  </p>

  <p>
    <strong>Quote asset volume:</strong>
    <%= kline.quote_asset_volume %>
  </p>

  <p>
    <strong>Number of trades:</strong>
    <%= kline.number_of_trades %>
  </p>

  <p>
    <strong>Taker buy base asset volume:</strong>
    <%= kline.taker_buy_base_asset_volume %>
  </p>

  <p>
    <strong>Taker buy quote asset volume:</strong>
    <%= kline.taker_buy_quote_asset_volume %>
  </p>

</div>

app/views/klines/edit.html.erb
<h1>Editing kline</h1>

<%= render "form", kline: @kline %>

<br>

<div>
  <%= link_to "Show this kline", @kline %> |
  <%= link_to "Back to klines", klines_path %>
</div>

app/views/klines/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Klines</h1>

<div id="klines">
  <% @klines.each do |kline| %>
    <%= render kline %>
    <p>
      <%= link_to "Show this kline", kline %>
    </p>
  <% end %>
</div>

<%= link_to "New kline", new_kline_path %>

app/views/klines/new.html.erb
<h1>New kline</h1>

<%= render "form", kline: @kline %>

<br>

<div>
  <%= link_to "Back to klines", klines_path %>
</div>

app/views/klines/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @kline %>

<div>
  <%= link_to "Edit this kline", edit_kline_path(@kline) %> |
  <%= link_to "Back to klines", klines_path %>

  <%= button_to "Destroy this kline", @kline, method: :delete %>
</div>