config/routes.rb
Rails.application.routes.draw do
  resources :klines do
    collection do
      post 'process_and_save'
    end
  end
  # Custom
  get 'crypto', to: 'crypto#index'
  get 'analyze', to: 'crypto#analyze'
  

  # Base
  resources :people
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'test', to: 'clients#test'

  devise_for :users
  # Allows us to use link_to for session destroy
  devise_scope :user do
    get "/users/sign_out", as: "sign_out", to: "devise/sessions#destroy"
  end

  # Defines the root path route ("/")
  root "pages#home"
end

app/controllers/crypto_controller.rb
class CryptoController < ApplicationController
  def index
    @assets = [ 'BTCUSDT', 'DOGEUSDT' ]
    timestamp_ms = crypto_service.get_server_time[1]
    timestamp_s = timestamp_ms / 1000.0
    @server_time  = Time.at(timestamp_s)

    @account_info = crypto_service.get_account_info
  end

  def analyze
    @symbol = params[:symbol]
    @btc_ticker = crypto_service.get_ticker(@symbol)

    @history = Kline.where(symbol: @symbol).order(open_time: :desc)

    input_data = @history.map { |kline| { date_time: kline.open_time, close: kline.close } }
    @result_analysis = TechnicalAnalysis::Sma.calculate(input_data, period: 30, price_key: :close) if input_data.count > 0
  end

  private

  def crypto_service
    @crypto_service ||= CryptoService.new
  end
end

app/helpers/crypto_helper.rb
module CryptoHelper
end

app/views/crypto/analyze.html.erb
<h2>Historico</h2>

<h2><%= @symbol %> Ticker</h2>
<p id="btc-price">Price: <%= @btc_ticker[:lastPrice] %></p>
<%= button_to 'Actualizar', process_and_save_klines_path(symbol: @symbol), class: 'btn btn-primary' %>

<h1>Klines</h1>
<div class="table-responsive mt-3">
  <table class="table align-middle">
    <thead class="table-secondary">
    <tr>
      <th>Open Time</th>
      <th>Open</th>
      <th>High</th>
      <th>Low</th>
      <th>Close</th>
      <th>SMA</th>
      <th>Volume</th>
      <th>Close Time</th>
      <th>Quote Asset Volume</th>
      <th>Number of Trades</th>
      <th>Taker Buy Base Asset Volume</th>
      <th>Taker Buy Quote Asset Volume</th>
    </tr>
  </thead>

  <tbody>
    <% @history.each_with_index do |kline, index| %>
      <tr>
        <td><%= kline.open_time.strftime("%d/%m/%Y %H:%M:%S") %></td>
        <td><%= number_to_currency kline.open %></td>
        <td><%= number_to_currency kline.high %></td>
        <td><%= number_to_currency kline.low %></td>
        <td><%= number_to_currency kline.close %></td>
        <td><%= "#{number_to_currency @result_analysis[index].sma} | #{@result_analysis[index].date_time.strftime("%d/%m/%Y")}" if @result_analysis[index] %></td>
        <td><%= kline.volume %></td>
        <td><%= kline.close_time.strftime("%d/%m/%Y %H:%M:%S") %></td>
        <td><%= kline.quote_asset_volume %></td>
        <td><%= kline.number_of_trades %></td>
        <td><%= kline.taker_buy_base_asset_volume %></td>
        <td><%= kline.taker_buy_quote_asset_volume %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/crypto/index.html.erb
<!-- app/views/crypto/index.html.erb -->

<h1>Crypto Information</h1>

<h2>Server Time</h2>
<p><%= @server_time %></p>


<h1>Activos</h1>
<div class="table-responsive mt-3">
  <table class="table align-middle">
    <thead class="table-secondary">
    <tr>
      <th>Activo</th>
      <th>Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @assets.each_with_index do |asset, index| %>
      <tr>
        <td><%= asset %></td>
        <td><%= link_to 'Analizar', analyze_path(symbol: asset), class: 'btn btn-sm btn-primary' %></td>
      </tr>
    <% end %>
  </tbody>
</table>